experiment_name: yolo_world_coco
dataset_root: /workspace/data/coco
output_dir: /workspace/checkpoints/object_detection/yolo_world/yolo_world_coco

test:
  model_name: yolov8s-worldv2.pt
  img_size: 640
  batch_size: 8
  conf_threshold: 0.001
  iou_threshold: 0.6
  max_images: null
  device: "0"
