experiment_name: yolo11_pose_coco
dataset_root: /workspace/data/coco_pose
dataset_yaml: /workspace/config/pose_estimation/coco_pose_dataset.yaml
output_dir: /workspace/checkpoints/pose_estimation/yolo11_pose/yolo11_pose_coco
tuning_mode: grid

train:
  model_name: yolo11n-pose.pt
  img_size: 640
  epochs: 10
  patience: 5
  batch: 8
  workers: 4
  fraction: 1.0
  device: "0"

grid:
  model_names: [yolo11n-pose.pt, yolo11s-pose.pt]
  img_sizes: [640]
  epochs: 10
  patience: 5
  batch: 8
  workers: 4
  fraction: 1.0

test:
  max_images: null
